### ISSUE TITLE
tiles.codefor.de gibt 502 Status Code

### ISSUE THREAD

**Issue by HT43-bqxFqB** [jochenklar/berlin-maps#10]
Hi @jochenklar,

ich weiß nicht ob ich bei dir und in diesem Repo hier an der richtigen Stelle bin. Aktuell liefer tiles.codefor.de für alle Openstreetmap tiles ein 502 aus. Fall es etwas bringt, kann ich auch bei der Fehleranalyse unterstützen.
Wenn das Repo hier der falsche Ort kann ich das Issue auch wo anders machen. Habe leider nur in der codefor.de Orga kein Repo für die tiles gefunden.

LG,
Martin

**Comment by jochenklar** [comment]
Hi, ja ich bin grade dran das zu reparieren. Die VM hat was abbekommen, ich glaube weil zu viele Files gecached worden sind.

Das mit den 3 Repos ist schwierig ich weis, ich denk mir was aus.

**Comment by jochenklar** [comment]
For future reference: http://technik.line5.de/2017/start-job-running/

**Comment by jochenklar** [comment]
Ok geht wieder.

```
0 4 * * 1 /srv/tiles/tilestache/env/bin/tilestache-clean.py -q -c /srv/tiles/tilestache/tilestache.cfg -l ALL 16 17 18 19 20
```

kommt jetzt in den crontab.

**Comment by HT43-bqxFqB** [comment]
Hab vielen Dank :)
